### ISSUE TITLE
求助：gio-webjs-sdk/gdp-full 未找到

### ISSUE THREAD

**Issue by nwulqx** [growingio/growingio-sdk-webjs-autotracker#1]
node 版本：v16.20.1
打包工具：vite
使用es modules 引入
<img width="1097" alt="企业微信截图_7c6cfcb3-1481-40ea-b083-6f0b98d2aed7" src="https://github.com/growingio/growingio-sdk-webjs-autotracker/assets/12780185/94e20df1-766a-4f78-a76f-6eb2c13f495c">

**Comment by Anoiing** [comment]
很抱歉，由于我们再master分支上提交了整个源代码的目录，提交以后只考虑了gdp.js的引用，没有考虑到原来直接引用其他js的路径配置，给您造成了不便。下次4.1.1发布时我们会尝试修复这个问题。4.1.0的版本，请先引用 "gio-webjs-sdk/dist/gdp-full.js"路径；或直接用按需引用的gdp.js。
